### ISSUE TITLE
Add a template file too when creating an action handler

### ISSUE THREAD

**Issue by akrabat** [zendframework/zend-expressive-tooling#50]
Related to #42, when creating a middleware actions with a factory, It would be lovely I could also get it to automatically create the template file for the action in the right folder, inject the template renderer into the the action via it’s factory and add something along the lines of `return new HtmlResponse($this->template->render('app::{name-in-dash-case}', []));` to the method that it is creating.

I expect that this is another switch and if it's set, then the create-a-factory switch from #42 is implicitly set too.

**Comment by weierophinney** [comment]
My plan will be to add a switch, `--with-template`, which will enable this. I'll also add an option `--template-namespace` to allow specifying the template namespace explicitly (instead of attempting to guess it from the class namespace).

**Comment by weierophinney** [comment]
I was about to look into this, and there are a few details I'm unsure of.

First, where should I place the template, exactly?

If the middleware or hander is in a module, then it would go in that module's `templates` directory... but how do I know if it's in a module? I suppose I could check to see if the path to the generated file matches `src/[^/]+/src/`.

And how do I know what the namespace is? If I've determined the class I've created belongs to a module, I suppose I could look at the `[^/]+` segment to determine that, and otherwise look at the first path segment following an initial `src/` match.

So, with those notes, here's what I propose:

- We look for `src/(?P<namespace>[^/]+)/(?P<isModule>src/)?`. This will tell us if we have a module, and give us the root namespace.
- We normalize the namespace by casting it to lowercase dash-separated words.
- We normalize the template name by stripping off `Middleware` or `Handler` suffixes from the class name, and casting it to lowercase dash-separated words.
- If the class generated IS in a module, we put the template file in the module's `templates/` subdirectory.
- If the class generated IS NOT in a module, we put the template file in the root `templates/{template namespace}/` directory (which we create if it does not exist).

Thoughts?

**Comment by geerteltink** [comment]
I understand why you would want to place the `./templates` in the templates dir. However, not everyone uses that structure. For example, I use something like this:

```
- res
    - assets
        - css | scss
        - js
        - img
    - templates
```

So you need to grab the templates folder from the config somehow to make it useful for everyone.

**Comment by michalbundyra** [comment]
Agree with @xtreamwayz, we should fetch the template path from the configuration if possible, otherwise we should have argument to provide the path.

**Comment by akrabat** [comment]
At a minimum, it needs to put it where the skeleton puts it. It would be lovely to work it out from configuration, but practically, the people who deviate from the skeleton are advanced users and a tiny minority. A command line option for those people would be nice to have though.

**Comment by akrabat** [comment]
Also, the normalisation logic looks good to me.

**Comment by weierophinney** [comment]
One other consideration, brought up by @ezimuel during a call we had today: the template suffix will need to vary based on the template engine and/or configured suffix.

**Comment by adamculp** [comment]
Could this be a little smarter in some way? Meaning, if templates are already part of an app `--with-template` is implied and a `--without-template` would be available. Likewise, if templates are not part of an app run without unless a `--with-template` flag is used, because...no templates needed (as in an API)

**Comment by weierophinney** [comment]
> Could this be a little smarter in some way? Meaning, if templates are already part of an app --with-template is implied and a --without-template would be available. Likewise, if templates are not part of an app run without unless a --with-template flag is used, because...no templates needed (as in an API)

The latter case was the main reason I was suggesting this as an opt-in facility, as templates may not be present.

I _should_ be able to do this at the command level; I'll investigate once I get template generation working locally.

**Comment by weierophinney** [comment]
@adamculp I've got things working locally in terms of initial template generation, and realized that your idea boils down to this:

- If a `TemplateRendererInterface` service is available, we would expose a `--without-template` flag, and a `--with-template-namespace` flag, and potentially a `--with-template=` option (to specify the template _name_).
- If no `TemplateRendererInterface` service is available, we would simply not generate a template, nor offer any flags for doing so.

I should be able to wrap this up tomorrow.

**Comment by weierophinney** [comment]
I've opened #63 with a potential implementation; please review!

**Comment by weierophinney** [comment]
Completed in #63, and will release with next 1.0.0 alpha release.
